name: twitch_best_practices
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  #core
  path_provider: ^2.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^5.1.0
  build_runner: ^2.4.6
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
